### ISSUE TITLE
Could not use in production mode

### ISSUE THREAD

**Issue by chocoford** [StarLederer/vite-plugin-fs#11]
I use it with Vite v3.0.9
```
[commonjs--resolver] virtual:fs imported in production code, that is not allowed. It is likely caused by importing vite-plugin-fs/browser. Please find a way not to do that, making a vite plugin is a great start.
```

**Comment by StarLederer** [comment]
Than you creating the first issue on this repo, very happy to see someone showing interest!

I see you already figured it out yourself, but could you please explain why you wanted to use vite-plugin-fs in prod mode? What was the intended user experience? Maybe I can help you find an alternative solution or see if your use-case is something that vite-plugin-fs should include out of the box
