### ISSUE TITLE
fs.stat error

### ISSUE THREAD

**Issue by deepkolos** [StarLederer/vite-plugin-fs#17]
<img width="617" alt="image" src="https://github.com/StarLederer/vite-plugin-fs/assets/12824616/c41a4f8c-aea4-4bcb-9479-1f5d19cecef4">

**Comment by StarLederer** [comment]
You closed the issue. Did you manage to fix this? What was the cause? Maybe I can add a mention of the problem you were experiencing in the documentation so others can get it out of the way quicker

**Comment by deepkolos** [comment]
the file does't exist then throw an error, i thought the api will return `undefined` or `null` in this situation. 

`fs.writeFile` does't support File yet which i will submit a PR later.

and abstraction's d.ts can be improve, i had to read code to realize this behavior

<img width="572" alt="image" src="https://github.com/StarLederer/vite-plugin-fs/assets/12824616/fa9ba749-df2a-4a96-9e3d-ad5d0d12f3d3">
